(function () {
  "use strict";

  const commonSources = {
    linear: {
      title: "MIT OpenCourseWare · 18.06SC Linear Algebra",
      url: "https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/",
      note: "Matrisler, alt uzaylar, özdeğerler ve uygulamalar için lisans dersi.",
    },
    ode: {
      title: "MIT OpenCourseWare · 18.03SC Differential Equations",
      url: "https://ocw.mit.edu/courses/18-03sc-differential-equations-fall-2011/",
      note: "Birinci ve ikinci mertebe denklemler, sistemler ve faz düzlemi.",
    },
    calculus: {
      title: "OpenStax · Calculus Volume 3",
      url: "https://openstax.org/details/books/calculus-volume-3",
      note: "Çok değişkenli fonksiyonlar, vektör kalkülüsü ve uygulamalar.",
    },
    physics1: {
      title: "OpenStax · University Physics Volume 1",
      url: "https://openstax.org/details/books/university-physics-volume-1",
      note: "Mekanik, salınımlar, dalgalar ve termodinamik için açık ders kitabı.",
    },
    physics2: {
      title: "OpenStax · University Physics Volume 2",
      url: "https://openstax.org/details/books/university-physics-volume-2",
      note: "Elektrik, manyetizma ve elektromanyetik dalgalar.",
    },
    chemistry: {
      title: "OpenStax · Chemistry 2e",
      url: "https://openstax.org/details/books/chemistry-2e",
      note: "Termodinamik, denge, kinetik ve elektrokimya bölümleri.",
    },
    biology: {
      title: "OpenStax · Biology 2e",
      url: "https://openstax.org/details/books/biology-2e",
      note: "Moleküler biyoloji, gen ifadesi ve hücresel düzenleme.",
    },
    algorithms: {
      title: "MIT OpenCourseWare · 6.006 Introduction to Algorithms",
      url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/",
      note: "Algoritmik düşünme, veri yapıları ve karmaşıklık analizi.",
    },
  };

  window.STEM_CONTENT = {
    "lineer-cebir-ve-ozdegerler": {
      mark: "A",
      field: "Matematiksel yöntemler · Durak 01",
      title: "Lineer cebir ve özdeğerler",
      description:
        "Matrisleri sayı tabloları olarak değil, uzayı dönüştüren makineler olarak gör; özvektörleri ve özdeğerleri etkileşimli laboratuvarla keşfet.",
      question:
        "Bir dönüşüm uzaydaki hemen her yönü döndürüp bükerken neden bazı özel yönler kendi doğrultusunda kalır?",
      questionDetail:
        "Lineer cebirin temel nesnesi matris değil, lineer dönüşümdür. Matris yalnızca seçtiğimiz baza göre bu dönüşümün koordinat kaydıdır. Bu bakış; titreşim kiplerinden veri sıkıştırmaya, kuantum mekaniğinden arama motorlarına kadar aynı fikri taşır.",
      level: "Lise sonu–Lisans",
      duration: "65 dakika",
      labLabel: "2×2 dönüşüm tezgâhı",
      prerequisites: [
        { href: "vektorler.html", label: "Vektörler" },
        { href: "matris-donusumleri.html", label: "Matris dönüşümleri" },
      ],
      goals: [
        ["Dönüşüm olarak düşün", "Aynı matrisin bütün vektörlere uygulanan tek bir kural olduğunu geometrik olarak açıkla."],
        ["Baz ve koordinatı ayır", "Vektörün kendisiyle onu anlatmak için kullandığımız sayı listesinin aynı şey olmadığını fark et."],
        ["Özçifti yorumla", "Av = λv eşitliğini, doğrultusu korunup yalnız ölçeklenen özel yön olarak oku."],
        ["Uygulama kur", "Tekrarlı dönüşümlerde en büyük mutlak özdeğerin uzun dönem davranışını neden baskıladığını açıkla."],
      ],
      sections: [
        {
          kicker: "1 · Matrisin geometrisi",
          title: "Sayı tablosundan dönüşüm makinesine",
          paragraphs: [
            "İki boyutta bir vektörü <strong>v = (x, y)</strong> olarak yazalım. 2×2 bir A matrisi bu vektörü yeni bir Av vektörüne gönderir. Matrisin ilk sütunu (1,0) baz vektörünün, ikinci sütunu (0,1) baz vektörünün nereye gittiğini söyler. Lineerlik nedeniyle diğer bütün vektörlerin görüntüsü bu iki sonucun uygun toplamıdır.",
            "Lineer dönüşüm, toplama ve sayıyla çarpmayı korur: A(u+v)=Au+Av ve A(cv)=cAv. Bu yüzden orijini başka bir noktaya taşıyan öteleme, iki boyutlu vektörler üzerinde tek başına lineer değildir. Buna karşılık döndürme, yansıtma, kesme ve eksenler boyunca ölçekleme lineer dönüşümlerdir.",
            "<strong>Determinant</strong>, dönüşümün yönlü alanı hangi katsayıyla değiştirdiğini ölçer. |det A|=2 ise her küçük alan iki katına çıkar. det A=0 ise düzlemin en az bir yönü çöker; dönüşüm tersinir değildir. Determinantın negatif olması yönelimin ters döndüğünü gösterir.",
          ],
          equation: "A = [[a, b], [c, d]], &nbsp; Av = (ax + by, cx + dy)",
          equationNote: "Sütunlar, baz vektörlerinin görüntüleridir. det(A)=ad−bc yönlü alan ölçeğidir.",
        },
        {
          kicker: "2 · Özel doğrultular",
          title: "Özvektör neyi değişmeden bırakır?",
          paragraphs: [
            "Sıfırdan farklı bir v vektörü dönüşümden sonra aynı doğru üzerinde kalıyorsa v bir <strong>özvektör</strong>, ölçek katsayısı λ ise ona ait <strong>özdeğer</strong>dir. λ>1 uzama, 0<λ<1 kısalma, λ<0 ise ölçeklemeye ek olarak yönün ters dönmesi demektir. λ=0 olduğunda o yön sıfıra çöker.",
            "Av=λv eşitliği (A−λI)v=0 biçimine getirilir. Sıfırdan farklı çözüm bulunabilmesi için A−λI matrisinin tersinir olmaması, yani determinantının sıfır olması gerekir. det(A−λI)=0 denklemi <strong>karakteristik denklem</strong>dir.",
            "Her gerçek matrisin gerçek özvektörü olmak zorunda değildir. Örneğin düzlemde 90° döndürme hiçbir gerçek doğrultuyu kendisi üzerinde bırakmaz; özdeğerler karmaşık sayılardır. Ayrıca bir matrisin yeterli sayıda bağımsız özvektörü olmayabilir; o zaman köşegenleştirme mümkün değildir.",
          ],
          equation: "Av = λv &nbsp; ⇔ &nbsp; det(A − λI) = 0",
          equationNote: "Bu eşdeğerliğin sağ tarafı özdeğer adaylarını, ardından boş uzay hesabı özvektörleri verir.",
        },
        {
          kicker: "3 · Baz değiştirmek",
          title: "Doğru koordinat sistemi problemi sadeleştirir",
          paragraphs: [
            "Bir vektör uzayın geometrik nesnesidir; koordinatları seçilen baza bağlıdır. Aynı ok, standart bazda (2,1), başka bir bazda farklı iki sayıyla temsil edilebilir. Baz değişimi fiziksel vektörü değil, onun betimlenişini değiştirir.",
            "A matrisi yeterli sayıda bağımsız özvektöre sahipse bu vektörleri baz olarak seçebiliriz. Bu bazda dönüşüm D köşegen matrisine dönüşür: A=PDP⁻¹. D'nin köşegeninde özdeğerler bulunur. Böylece A'nın n kez uygulanması Aⁿ=PDⁿP⁻¹ olur; karmaşık matris çarpımları özdeğerleri n'inci kuvvete yükseltmeye indirgenir.",
            "Bu fikir salınan yapıların normal kiplerinde, popülasyon modellerinde ve Markov zincirlerinin durağan dağılımlarında ortaya çıkar. Uzun vadede mutlak değeri en büyük özdeğere ait bileşen genellikle baskın olur; fakat eşit büyüklükler, karmaşık değerler veya köşegenleştirilemeyen matrisler daha dikkatli analiz gerektirir.",
          ],
          note: "Model köprüsü: Özdeğer yalnızca bir hesap sonucu değildir; sistemin doğal büyüme, sönme veya titreşim kipini işaret eder.",
        },
        {
          kicker: "4 · İç çarpım ve izdüşüm",
          title: "En iyi yaklaşım neden diklikten doğar?",
          paragraphs: [
            "Bir u vektörünün v doğrultusundaki izdüşümü, u ile v arasındaki iç çarpımla bulunur. Kalan hata v'ye diktir. Birden çok baz vektörüne genellendiğinde bu fikir en küçük kareler yöntemini doğurur: tam çözülemeyen Ax=b sistemi için ||Ax−b|| hatasını en aza indiren çözüm aranır.",
            "Normal denklemler AᵀAx=Aᵀb biçimindedir; geometrik anlamı, hata vektörünün A'nın sütun uzayına dik olmasıdır. Sayısal hesapta normal denklemler her zaman en kararlı yol değildir; QR veya tekil değer ayrışımı daha güvenilir olabilir. Matematiksel eşitlik ile iyi hesaplama yöntemi aynı soru değildir.",
          ],
          equation: "projᵥ(u) = ((u·v)/(v·v))v &nbsp; ve &nbsp; Aᵀ(Ax−b)=0",
          equationNote: "En küçük kareler çözümünde artık r=Ax−b, A'nın her sütununa diktir.",
        },
      ],
      worked: {
        title: "Çözülmüş örnek · İki eksende farklı büyüme",
        intro: "A = [[3,1],[0,2]] dönüşümünün özdeğerlerini ve özvektör yönlerini bulalım.",
        steps: [
          "Karakteristik determinant: det(A−λI)=(3−λ)(2−λ)=0. Özdeğerler λ₁=3 ve λ₂=2.",
          "λ=3 için (A−3I)v=0 denklemi y=0 verir; örneğin v₁=(1,0). Bu yön her adımda üç katına çıkar.",
          "λ=2 için x+y=0; örneğin v₂=(−1,1). Bu doğrultu her adımda iki katına çıkar.",
          "Başlangıç vektörünün v₁ bileşeni sıfır değilse tekrarlı uygulamada 3ⁿ büyümesi 2ⁿ büyümesini geçer; yön giderek x eksenine yaklaşır.",
        ],
      },
      misconceptions: [
        ["Matris yalnızca denklem çözmek için bir sayı tablosudur.", "Matris, seçilen bazda bir lineer dönüşümün temsilidir; aynı dönüşüm başka bazda başka matrisle yazılır."],
        ["Her matrisin iki gerçek ve farklı özvektör yönü vardır.", "Gerçek özvektör bulunmayabilir veya tek bağımsız yön bulunabilir; matris her zaman köşegenleştirilemez."],
      ],
      limits: [
        ["Lineerlik sınırı", "Gerçek sistemler çoğu zaman doğrusal değildir. Lineer cebir yine de bir çalışma noktasının yakınında yerel yaklaşım sağlar."],
        ["Sayısal duyarlılık", "Birbirine çok yakın özdeğerler ve kötü koşullu bazlar, küçük ölçüm/yuvarlama hatalarını büyütebilir."],
      ],
      lab: { type: "matrix", title: "Bir dönüşümün doğal yönlerini ara", intro: "Matris elemanlarını değiştir. Izgaranın ve hareketli vektörün dönüşümünü izle; gerçek özdeğer varsa laboratuvar özel doğrultuları işaretler." },
      connections: [
        ["diferansiyel-denklemler.html", "Diferansiyel denklemler", "Lineer sistemlerin faz düzlemini özdeğerlerle sınıflandır."],
        ["kuantum-mekanigi.html", "Kuantum mekaniği", "Gözlenebilirleri işleç ve özdurum diliyle yorumla."],
        ["makine-ogrenmesi-derin-ogrenme-llm.html", "Makine öğrenmesi", "Veriyi vektör uzayında temsil et; izdüşüm ve optimizasyon bağlantısını kur."],
      ],
      quiz: [
        ["Bir 2×2 matrisin determinantı sıfırsa hangisi kesinlikle doğrudur?", ["İki özdeğeri de sıfırdır", "Dönüşüm alanı bir doğruya ya da noktaya çökertir", "Matris simetriktir"], 1, "det A=0, dönüşümün tersinir olmadığını ve alan ölçeğinin sıfır olduğunu söyler; bütün özdeğerlerin sıfır olması gerekmez."],
        ["Av=−2v eşitliğinde v için ne söylenir?", ["Yönü korunarak iki kat uzar", "Doğrultusu korunur, yönü ters dönüp iki kat uzar", "Sıfıra gider"], 1, "Negatif özdeğer doğrultuyu korur ama vektör yönünü ters çevirir; mutlak değer ölçeği verir."],
        ["A=PDP⁻¹ yazımı neden kullanışlıdır?", ["Determinantı her zaman 1 yapar", "Aⁿ hesabını D'nin köşegen elemanlarının kuvvetlerine indirger", "A'yı doğrusal olmayan yapar"], 1, "Köşegen matrisin kuvveti kolaydır: yalnızca köşegen elemanları üslenir."],
      ],
      glossary: [["Baz", "Uzaydaki her vektörü tek biçimde üreten bağımsız vektörler kümesi."], ["Özvektör", "Lineer dönüşüm altında doğrultusu değişmeyen sıfırdan farklı vektör."], ["Özdeğer", "Özvektörün dönüşüm altındaki ölçek katsayısı."], ["Koşul sayısı", "Girdideki küçük değişimlerin sonuca ne ölçüde büyüyerek yansıyabileceğinin göstergesi."]],
      sources: [commonSources.linear],
    },

    "cok-degiskenli-kalkulus": {
      mark: "∇",
      field: "Matematiksel yöntemler · Durak 02",
      title: "Çok değişkenli kalkülüs",
      description: "Birden çok değişkenin birlikte değiştirdiği yüzeyleri, kısmi türevi, gradyanı ve çok katlı integralleri etkileşimli bir seviye haritasıyla öğren.",
      question: "Bir dağın üzerindeyken en dik yükseliş yönünü, bütün yolları tek tek denemeden nasıl bulursun?",
      questionDetail: "Tek değişkenli türev bir eğrinin anlık eğimini verir. Gerçek sistemlerde sıcaklık, basınç, enerji veya kayıp birden çok girdiye bağlıdır. Gradyan, bu çok boyutlu değişim manzarasında hem en hızlı artış yönünü hem de artış hızını kodlar.",
      level: "Lise sonu–Lisans",
      duration: "60 dakika",
      labLabel: "Gradyan ve seviye eğrileri",
      prerequisites: [{ href: "turev.html", label: "Türev" }, { href: "vektorler.html", label: "Vektörler" }, { href: "integral.html", label: "İntegral" }],
      goals: [
        ["Yüzeyi oku", "z=f(x,y) grafiği ile seviye eğrileri arasındaki ilişkiyi kur."],
        ["Kısmi türev al", "Bir değişkeni değiştirirken diğerini sabit tutmanın anlamını açıkla."],
        ["Gradyanı yorumla", "∇f vektörünü en hızlı artış yönü ve yerel değişim oranı olarak kullan."],
        ["Birikimi genelle", "Çift katlı integrali küçük alan parçalarının toplamının limiti olarak yorumla."],
      ],
      sections: [
        { kicker: "1 · Eğriden yüzeye", title: "Bir çıktı, birden çok girdi", paragraphs: [
          "f(x,y) fonksiyonu düzlemdeki her (x,y) noktasına bir sayı atar. Bu sayı yükseklikse üç boyutlu bir yüzey; sıcaklıksa renkli bir harita olarak gösterilebilir. f(x,y)=sabit koşulunu sağlayan noktalar <strong>seviye eğrilerini</strong> oluşturur. Bir topoğrafya haritasındaki eş yükselti çizgileri bunun tanıdık örneğidir.",
          "Bir fonksiyonun limiti (x,y) noktası hedefe hangi yoldan yaklaşırsa yaklaşılsın aynı değere gitmelidir. Yalnız x ekseni ve y ekseni boyunca bakmak yeterli değildir; farklı eğriler farklı limitler verebilir. Bu, çok değişkenli sürekliliğin tek boyuttan daha zengin olmasının ilk işaretidir.",
        ], equation: "z=f(x,y), &nbsp; seviye eğrisi: f(x,y)=c", equationNote: "Seviye eğrileri sıklaştıkça yüzey genellikle daha diktir; eşit c aralıkları kullanıldığı varsayılır." },
        { kicker: "2 · Yerel değişim", title: "Kısmi türevler ve yönlü türev", paragraphs: [
          "∂f/∂x hesaplanırken y sabit tutulur ve x yönündeki anlık değişim ölçülür. ∂f/∂y ise x sabitken y yönünü inceler. Bu iki sayı, seçilen koordinat eksenlerindeki yerel eğimleri verir; fakat başka bir yöne gitmek istediğimizde <strong>yönlü türev</strong> gerekir.",
          "Birim u yönündeki türev Dᵤf=∇f·u'dur. İç çarpım en büyük olduğunda u, gradyanla aynı yöndedir. Bu nedenle ∇f en hızlı artış yönünü; −∇f en hızlı azalış yönünü gösterir. Seviye eğrisi boyunca f değişmediği için gradyan bu eğriye diktir.",
        ], equation: "∇f=(∂f/∂x, ∂f/∂y), &nbsp; Dᵤf=∇f·u", equationNote: "u birim vektör olmalıdır; aksi hâlde sonuç yönle birlikte adım büyüklüğünü de içerir." },
        { kicker: "3 · Zincir kuralı", title: "Yollar ve bağımlılıklar boyunca değişim", paragraphs: [
          "Bir parçacık r(t)=(x(t),y(t)) yolunda hareket ederken ölçtüğü sıcaklık f(x(t),y(t)) olsun. Zamana göre değişim yalnız f'nin değil, parçacığın her eksendeki hızının da sonucudur. Çok değişkenli zincir kuralı bu etkileri toplar.",
          "Aynı düşünce daha çok değişken için Jacobian matrisiyle ifade edilir. Jacobian, çok girdili–çok çıktılı bir fonksiyonun belirli bir nokta yakınındaki en iyi lineer yaklaşımıdır. Sinir ağlarında geriye yayılım da katman katman uygulanan zincir kuralıdır.",
        ], equation: "df/dt = (∂f/∂x)(dx/dt) + (∂f/∂y)(dy/dt) = ∇f·r′(t)", equationNote: "Bu eşitlik fonksiyonlar ilgili noktada türevlenebilir olduğunda geçerlidir." },
        { kicker: "4 · Alan ve hacim boyunca toplamak", title: "Çift integral ve koordinat seçimi", paragraphs: [
          "Tek integral bir aralıktaki küçük katkıları toplar; çift integral bir bölgeyi küçük alan parçalarına ayırır. ∬ᴿ f(x,y)dA ifadesi, yüzey altındaki yönlü hacmi veya yüzey yoğunluğu verilmiş bir levhanın toplam kütlesini hesaplayabilir.",
          "Dairesel simetrili bir bölgede Kartezyen dikdörtgenler yerine kutupsal dilim kullanmak hesabı sadeleştirir. Dönüşüm yapılırken alan elemanı dA=r dr dθ olur. Fazladan r, dış halkaların aynı açı ve kalınlıkta daha büyük alana sahip olmasından gelir; bu faktörü unutmak geometrik toplamı bozar.",
        ], equation: "∬ᴿ f(x,y)dA; &nbsp; x=r cosθ, y=r sinθ ⇒ dA=r dr dθ", equationNote: "Genel değişken dönüşümünde alan/hacim ölçeğini Jacobian determinantının mutlak değeri verir." },
      ],
      worked: { title: "Çözülmüş örnek · En dik yükseliş", intro: "f(x,y)=x²+2y² yüzeyinde (1,−1) noktasındayız.", steps: ["Kısmi türevler: fₓ=2x ve fᵧ=4y.", "Noktada gradyan ∇f(1,−1)=(2,−4). En hızlı artış bu yöndedir.", "Artış hızının en büyük değeri ||∇f||=√20'dir.", "Aynı noktadan seviye eğrisi boyunca gitmek için (2,−4)'e dik bir yön, örneğin (2,1) seçilebilir; ilk mertebede f değişmez."] },
      misconceptions: [["Kısmi türev alırken diğer değişken yok sayılır.", "Diğer değişken yok olmaz; incelenen yerel değişim boyunca sabit tutulur."], ["Gradyan yüzeyin yukarı doğru üç boyutlu teğetidir.", "∇f girdi düzleminde yaşar; en hızlı artış yönünü gösterir. Yüzeydeki teğet vektörle aynı nesne değildir."]],
      limits: [["Yerel bilgi", "Gradyan yalnız bulunduğun noktadaki en dik yönü verir; büyük bir adımda eğrilik nedeniyle hedefi aşabilirsin."], ["Türevlenebilirlik", "Köşe, sıçrama veya tekilliklerde gradyan tanımsız olabilir; kısmi türevlerin varlığı tek başına türevlenebilirliği garanti etmez."]],
      lab: { type: "gradient", title: "Değişim manzarasında yürüyüş", intro: "Noktayı ve yüzey biçimini değiştir. Seviye çizgilerini, gradyanı ve seçtiğin yürüyüş yönündeki türevi aynı anda izle." },
      connections: [["lineer-cebir-ve-ozdegerler.html", "Lineer cebir", "Jacobianı yerel bir lineer dönüşüm olarak oku."], ["diferansiyel-denklemler.html", "Diferansiyel denklemler", "Bir vektör alanının ürettiği akış çizgilerini izle."], ["makine-ogrenmesi-derin-ogrenme-llm.html", "Makine öğrenmesi", "Kayıp yüzeyinde gradyan inişinin neden çalıştığını sorgula."]],
      quiz: [
        ["∇f bir seviye eğrisine nasıl yönelir?", ["Teğettir", "Diktir", "Her zaman x eksenine paraleldir"], 1, "Seviye eğrisi boyunca f sabit olduğundan bu yöndeki türev sıfırdır; gradyan teğete diktir."],
        ["Yönlü türev Dᵤf'nin yalnız yönü ölçmesi için u nasıl olmalıdır?", ["Birim vektör", "Sıfır vektörü", "Gradyana dik olmayan herhangi bir vektör"], 0, "u'nun uzunluğu 1 değilse sonuç yönün yanında adım ölçeğini de taşır."],
        ["Kutupsal koordinatlarda dA neden r dr dθ'dır?", ["Çünkü açı derece cinsindendir", "Dıştaki açısal dilim daha uzun yay içerir", "Çünkü f her zaman r ile çarpılır"], 1, "Yay uzunluğu yaklaşık r dθ olduğundan küçük dilimin alanı dr·r dθ'dır."],
      ],
      glossary: [["Seviye eğrisi", "Fonksiyonun aynı değeri aldığı noktaların oluşturduğu eğri."], ["Gradyan", "Kısmi türevlerden oluşan, en hızlı artışı gösteren vektör."], ["Jacobian", "Çok girdili bir dönüşümün yerel türev matrisi."], ["Yönlü türev", "Fonksiyonun seçilen birim yön boyunca anlık değişim oranı."]],
      sources: [commonSources.calculus],
    },

    "diferansiyel-denklemler": {
      mark: "ẋ",
      field: "Matematiksel yöntemler · Durak 03",
      title: "Diferansiyel denklemler ve dinamik sistemler",
      description: "Bir sistemin anlık değişim kuralından bütün zaman öyküsünü çıkar; denge, kararlılık, faz düzlemi ve sayısal çözümü keşfet.",
      question: "Bir sistemin bugün nasıl değiştiğini biliyorsak yarın nerede olacağını ne ölçüde öngörebiliriz?",
      questionDetail: "Diferansiyel denklem, bilinmeyen bir sayı yerine bilinmeyen bir fonksiyon arar. Doğa yasaları çoğu zaman ‘durumun değişim hızı şu anki duruma bağlıdır’ der. Çözüm, bu yerel kuralı başlangıç koşuluyla bütün bir zaman çizgisine dönüştürür.",
      level: "Lisans başlangıcı",
      duration: "70 dakika",
      labLabel: "Salınım ve faz düzlemi",
      prerequisites: [{ href: "turev.html", label: "Türev" }, { href: "integral.html", label: "İntegral" }, { href: "lineer-cebir-ve-ozdegerler.html", label: "Lineer cebir" }],
      goals: [["Model kur", "Sözel bir değişim kuralını diferansiyel denklem ve başlangıç koşuluna çevir."], ["Çözümü yorumla", "Çözüm ailesi ile belirli başlangıç değerinin seçtiği çözümü ayır."], ["Faz uzayını oku", "Zamana karşı grafik yerine durum değişkenlerinin birbirine karşı grafiğini kullan."], ["Yaklaşımı sorgula", "Euler adımının neden hata ürettiğini ve adım küçüldükçe ne değiştiğini açıkla."]],
      sections: [
        { kicker: "1 · Değişim yasası", title: "Denklem, çözüm ve başlangıç koşulu", paragraphs: ["dy/dt=f(t,y) denklemi, her (t,y) noktasında çözüm eğrisinin eğimini söyler. Bir <strong>eğim alanı</strong> bu yerel talimatları oklarla gösterir. Çözüm eğrisi her noktada ilgili oka teğet ilerler.", "dy/dt=ky için y=Ceᵏᵗ bir çözüm ailesidir. C sabiti başlangıç koşuluyla belirlenir. k>0 büyüme, k<0 sönme üretir. Ancak sınırsız üstel büyüme çoğu gerçek popülasyon için yalnız kaynak kısıtı hissedilmeden önce geçerli bir yaklaşımdır."], equation: "dy/dt=ky, &nbsp; y(0)=y₀ ⇒ y(t)=y₀eᵏᵗ", equationNote: "Başlangıç koşulu bir çözüm ailesinden tek yörünge seçer; uygun düzenlilik koşulları altında çözüm yerel olarak tektir." },
        { kicker: "2 · Denge ve kararlılık", title: "Sistemi çözmeden davranışı görmek", paragraphs: ["Otonom y′=f(y) denkleminde f(y*)=0 olan y* değeri dengedir. Dengenin iki yanındaki işaretlere bakarak yörüngelerin yaklaşıp uzaklaştığını görebiliriz. Yakındaki başlangıçlar zamanla dengeye dönüyorsa denge kararlı; küçük sapmalar büyüyorsa kararsızdır.", "Lojistik model y′=ry(1−y/K), küçük y için üstel büyürken K taşıma kapasitesine yaklaştıkça büyümeyi yavaşlatır. y=0 ve y=K dengedir. r>0 için pozitif küçük başlangıçlar K'ya yaklaşır. Model yine de çevre dalgalanmalarını, yaş yapısını ve gecikmeleri dışarıda bırakır."], equation: "dy/dt=ry(1−y/K)", equationNote: "r içsel büyüme oranı, K modelde sabit kabul edilen taşıma kapasitesidir." },
        { kicker: "3 · İkinci mertebe ve sistemler", title: "Salınımı faz düzleminde okumak", paragraphs: ["Yay–kütle sistemi mx″+cx′+kx=F(t) denklemiyle modellenir. x konum, x′ hızdır. İkinci mertebe denklem x′=v ve v′=(F−cv−kx)/m biçiminde iki birinci mertebe denkleme çevrilebilir.", "Faz düzleminde yatay eksen x, düşey eksen v'dir. Sürtünmesiz sistem kapalı elipsler çizer; toplam enerji sabittir. Sönüm varsa yörünge orijine spiral olur. Dış kuvvetin frekansı doğal frekansa yaklaşınca rezonans görülebilir; sönüm sonlu genliği ve faz gecikmesini belirler."], equation: "mx″+cx′+kx=F(t), &nbsp; ω₀=√(k/m)", equationNote: "ω₀ ifadesi sönümsüz doğal açısal frekanstır; sönümlü titreşimin frekansı c'ye de bağlıdır." },
        { kicker: "4 · Sayısal düşünme", title: "Euler yöntemi ve hata", paragraphs: ["Çoğu diferansiyel denklemin kapalı biçimde çözümü yoktur. Euler yöntemi, mevcut noktadaki eğimi kısa bir h adımı boyunca sabit kabul eder: yₙ₊₁=yₙ+h f(tₙ,yₙ). Bu, teğet doğrularla çözümü parça parça izler.", "h küçüldükçe yerel yaklaşım genellikle iyileşir ama işlem sayısı artar ve yuvarlama hataları önem kazanabilir. Sert denklemlerde çok küçük adım gerekebilir; daha yüksek mertebeli Runge–Kutta veya örtük yöntemler tercih edilir. Bir sayısal çizgi, hata ve kararlılık analizi olmadan ‘gerçek çözüm’ değildir."], equation: "tₙ₊₁=tₙ+h, &nbsp; yₙ₊₁=yₙ+h f(tₙ,yₙ)", equationNote: "Euler yönteminin küresel hatası uygun koşullarda h mertebesindedir; h yarıya inince hata yaklaşık yarıya iner." },
      ],
      worked: { title: "Çözülmüş örnek · Soğuyan kahve", intro: "Oda 20 °C, kahve başlangıçta 80 °C ve Newton soğuma sabiti k=0,08 dk⁻¹ olsun.", steps: ["Model: T′=−k(T−20). Değişim sıcaklık farkıyla orantılıdır.", "Çözüm: T(t)=20+(80−20)e⁻⁰·⁰⁸ᵗ.", "10 dakika sonra T≈20+60e⁻⁰·⁸≈47,0 °C.", "Model; oda sıcaklığını sabit, kahveyi her yerde aynı sıcaklıkta ve k'yı değişmez kabul eder. Buharlaşma veya kap etkisi güçlü ise sapma beklenir."] },
      misconceptions: [["Diferansiyel denklem çözümü tek bir sayıdır.", "Çözüm çoğu zaman bir fonksiyon ailesidir; başlangıç/sınır koşulları belirli çözümü seçer."], ["Sayısal çözücü çok basamak gösteriyorsa sonuç o kadar doğrudur.", "Gösterilen basamak sayısı hata tahmini değildir; adım, yöntem ve problem duyarlılığı incelenmelidir."]],
      limits: [["Başlangıç duyarlılığı", "Doğrusal olmayan kaotik sistemlerde başlangıçtaki küçük belirsizlik uzun vadeli noktasal tahmini sınırlar."], ["Model seçimi", "Denklemi kusursuz çözmek, eksik ya da yanlış fiziksel varsayımı düzeltmez."]],
      lab: { type: "ode", title: "Sönüm, frekans ve faz portresi", intro: "Yay sabiti, sönüm ve başlangıç konumunu değiştir. x(t) grafiğiyle (x,v) faz yörüngesinin aynı hareketi nasıl farklı anlattığını karşılaştır." },
      connections: [["lineer-cebir-ve-ozdegerler.html", "Lineer cebir", "Sistem matrisinin özdeğerlerinden kararlılığı oku."], ["yay-kutle.html", "Yay–kütle", "İdeal harmonik hareketi deneysel sezgiyle bağla."], ["lorenz-cekici.html", "Lorenz çekicisi", "Doğrusal olmayan dinamikte kaos ve başlangıç duyarlılığını gör."]],
      quiz: [["y′=f(y) için bir denge noktası nasıl bulunur?", ["f(y)=1 çözülür", "f(y)=0 çözülür", "y her zaman türevlenir"], 1, "Dengede durum değişmediği için türev, dolayısıyla f(y*) sıfırdır."], ["Sönümlü yay sisteminin faz yörüngesi neden içe spiral olur?", ["Enerji çevreye aktarılır", "Kütle artar", "Zaman geriye akar"], 0, "Sönüm mekanik enerjiyi azaltır; hem konum hem hız salınımlarının genliği küçülür."], ["Euler yönteminde h'yi küçültmenin temel etkisi nedir?", ["Yerel doğrusal yaklaşım daha kısa aralıkta kullanılır", "Denklem otomatik olarak lineer olur", "Başlangıç koşulu silinir"], 0, "Daha kısa adım, eğimin adım boyunca sabit kalması yaklaşımını genellikle iyileştirir."]],
      glossary: [["Başlangıç koşulu", "Çözümün belirli bir andaki değerini belirten ek bilgi."], ["Faz uzayı", "Bir sistemin durum değişkenlerini koordinat olarak kullanan uzay."], ["Denge", "Zamanla değişmeyen durum."], ["Kararlılık", "Küçük başlangıç sapmalarının büyüyüp büyümediğine ilişkin özellik."]],
      sources: [commonSources.ode, commonSources.physics1],
    },

    "maxwell-denklemleri-ve-alanlar": {
      mark: "E",
      field: "İleri fizik · Durak 01",
      title: "Maxwell denklemleri ve alanlar",
      description: "Elektrik ve manyetik alanları tek bir kuramda birleştir; akı, dolaşım, indüksiyon ve ışığın elektromanyetik dalga oluşunu gör.",
      question: "Boş uzayda ilerleyen ışık, taşıyıcı bir madde olmadan kendi kendini nasıl sürdürebilir?",
      questionDetail: "Değişen elektrik alan manyetik alan, değişen manyetik alan elektrik alan üretir. Maxwell denklemleri yükleri ve akımları alanların kaynağına bağlarken, boşluktaki çözümleri ışık hızında yayılan dalgaları verir.",
      level: "Lise ileri–Lisans",
      duration: "75 dakika",
      labLabel: "Elektromanyetik dalga laboratuvarı",
      prerequisites: [{ href: "lorentz-kuvveti.html", label: "Lorentz kuvveti" }, { href: "manyetik-alan.html", label: "Manyetik alan" }, { href: "cok-degiskenli-kalkulus.html", label: "Vektör kalkülüsü" }],
      goals: [["Alanı tanımla", "Alanı uzayın her noktasına değer atayan fiziksel model olarak yorumla."], ["Akı ve dolaşımı ayır", "Kapalı yüzeyden geçen akıyla kapalı yol çevresindeki dolaşımın rollerini karşılaştır."], ["Dört yasayı birleştir", "Yük, akım ve zamanla değişen alanların hangi Maxwell denkleminde yer aldığını açıkla."], ["Dalga hızını çıkar", "Boşluk sabitleri ε₀ ve μ₀'ın ışık hızını nasıl belirlediğini ilişkilendir."]],
      sections: [
        { kicker: "1 · Alan fikri", title: "Uzaktan etki yerine yerel bir durum", paragraphs: ["Elektrik alan E, küçük bir pozitif test yükünün birim yük başına göreceği kuvveti; manyetik alan B ise hareketli yüklere etki eden Lorentz kuvvetinin manyetik bölümünü tanımlar. Alan, yalnız çizilmiş oklar değil, enerji ve momentum taşıyabilen fiziksel bir modeldir.", "Alan çizgileri görsel yardımcıdır: E çizgilerinin teğeti alan yönünü, çizgi yoğunluğu kabaca büyüklüğü gösterir. Çizgiler fiziksel teller değildir ve uzayda sayılabilir nesneler gibi düşünülmemelidir."], equation: "F=q(E+v×B)", equationNote: "Manyetik kuvvet hıza ve alana diktir; tek başına parçacığın kinetik enerjisini değiştirmez." },
        { kicker: "2 · Kaynaklar", title: "Gauss yasaları: kapalı yüzey ne görür?", paragraphs: ["Elektrik için Gauss yasası, kapalı bir yüzeyden çıkan toplam elektrik akısını içerideki net yüke bağlar. Yüzeyin biçimi fark etmez; simetri varsa alanı hesaplamayı çok kolaylaştırır.", "Manyetizma için kapalı bir yüzeyden net B akısı sıfırdır. Bu, gözlenen kuramda yalıtılmış manyetik tek kutup bulunmadığını ve manyetik alan çizgilerinin kapalı döngüler oluşturduğunu ifade eder. Bir mıknatısı kesmek kuzey ve güneyi ayırmaz; iki daha küçük dipol üretir."], equation: "∮ E·dA=Qᵢç/ε₀, &nbsp; ∮ B·dA=0", equationNote: "İntegral biçimleri sonlu yüzeyleri; diferansiyel biçimler aynı yasaların yerel kaynak yoğunluğunu anlatır." },
        { kicker: "3 · Değişen alanlar", title: "Faraday ve Ampère–Maxwell yasaları", paragraphs: ["Faraday yasası, bir devrenin sınırladığı yüzeyden geçen manyetik akı değiştiğinde kapalı yol boyunca elektrik alan dolaşımı oluştuğunu söyler. Eksi işareti Lenz yasasını kodlar: indüklenen etki, akı değişimine karşı koyacak yöndedir.", "Ampère yasasına Maxwell'in eklediği yer değiştirme akımı terimi, değişen elektrik akısının da manyetik alan ürettiğini gösterir. Bu düzeltme, kondansatör plakaları arasındaki boşlukta yük korunumu ile tutarlılığı sağlar ve elektromanyetik dalganın diğer yarısını tamamlar."], equation: "∮E·dl=−dΦᴮ/dt; &nbsp; ∮B·dl=μ₀I+μ₀ε₀ dΦᴱ/dt", equationNote: "Akı için seçilen yüzey normali ile kapalı yol yönü sağ el kuralıyla tutarlı olmalıdır." },
        { kicker: "4 · Işık", title: "Boşluktaki alan denklemi dalga üretir", paragraphs: ["Yük ve akım bulunmayan bölgede Maxwell denklemleri birleştirildiğinde E ve B için dalga denklemi çıkar. Dalganın hızı c=1/√(μ₀ε₀)'dır. Ölçülen değer ışık hızıyla aynıdır: ışık elektromanyetik dalgadır.", "Düzlem dalgada E ve B birbirine ve yayılma yönüne diktir. Alanlar aynı fazdadır ve büyüklükleri E=cB ilişkisini sağlar. Enerji akışının yönü Poynting vektörü S=(1/μ₀)E×B ile gösterilir. Gerçek ışık paketleri, sınırlar ve yakın alanlar düzlem dalgadan daha karmaşık olabilir."], equation: "∇²E=(1/c²)∂²E/∂t², &nbsp; c=1/√(μ₀ε₀)", equationNote: "Bu biçim doğrusal, homojen ve kaynaksız boşluk için geçerlidir; maddede hız ve sönüm ortam özelliklerine bağlıdır." },
      ],
      worked: { title: "Çözülmüş örnek · Bir radyo dalgasının ölçeği", intro: "Boşlukta f=100 MHz frekanslı bir elektromanyetik dalga düşünelim.", steps: ["Dalga boyu λ=c/f=(3,00×10⁸ m/s)/(1,00×10⁸ s⁻¹)=3,00 m.", "Elektrik alan genliği E₀=30 V/m ise B₀=E₀/c≈1,00×10⁻⁷ T.", "E ve B tepe değerlerine aynı anda ulaşır; yönleri birbirine ve yayılmaya diktir.", "Bu hesap düzlem dalga ve boşluk yaklaşımıdır. Antene çok yakın bölgede alan oranı ve geometrisi farklı olabilir."] },
      misconceptions: [["Elektrik alan varsa mutlaka yakınında yük vardır.", "Yükler E alanının kaynaklarından biridir; değişen manyetik alan da girdaplı E alanı üretebilir."], ["Manyetik alan iş yapmadığı için elektromanyetik dalga enerji taşımaz.", "Dalga enerjisi birlikte bulunan E ve B alanlarında depolanır; enerji akışı Poynting vektörüyle ifade edilir."]],
      limits: [["Klasik kuram", "Maxwell denklemleri klasik alanı olağanüstü doğrulukla açıklar; tek foton süreçleri kuantum elektrodinamiği gerektirir."], ["Düzlem dalga", "Laboratuvar yalnız uzak alan, homojen ortam ve tek frekanslı ideal dalga gösterir; kaynak yakınında veya maddede ek etkiler vardır."]],
      lab: { type: "em", title: "Birbirini üreten iki alan", intro: "Frekans, genlik ve fazı değiştir. E ile B'nin dik düzlemlerde, aynı fazda ve sabit E/B oranıyla ilerleyişini incele." },
      connections: [["kirinim-izgarasi.html", "Kırınım", "Dalga boyunun girişim desenini nasıl belirlediğini gör."], ["alternatif-akim.html", "Alternatif akım", "Zamanla değişen alanları devre frekans yanıtına bağla."], ["gorelilik-uzayzaman.html", "Özel görelilik", "Işık hızının değişmezliğinin uzay ve zaman ölçümlerini nasıl dönüştürdüğünü izle."]],
      quiz: [["Maxwell'in Ampère yasasına eklediği terim neyi temsil eder?", ["Değişen elektrik akısının manyetik alan üretmesini", "Manyetik tek kutupları", "Kütleçekim akısını"], 0, "Yer değiştirme akımı terimi değişen elektrik alanı manyetik dolaşıma bağlar."], ["Boşluktaki düzlem dalgada E, B ve yayılma yönü nasıldır?", ["Üçü paraleldir", "E ve B paralel, yayılmaya diktir", "Üçü birbirine diktir"], 2, "E×B enerji/yayılma yönünü verir; bu üç yön karşılıklı diktir."], ["∮B·dA=0 ne söyler?", ["B her yerde sıfırdır", "Kapalı yüzeyden net manyetik akı sıfırdır", "Mıknatıs enerji taşımaz"], 1, "Yüzeyden giren ve çıkan manyetik akı dengelenir; bu, B'nin sıfır olmasını gerektirmez."]],
      glossary: [["Alan", "Uzayın her noktasına fiziksel bir nicelik atayan model."], ["Akı", "Bir vektör alanının seçilen yüzeyden geçen yönlü miktarı."], ["Dolaşım", "Alan vektörünün kapalı yolun teğeti boyunca çizgi integrali."], ["Poynting vektörü", "Elektromanyetik enerji akısının yönünü ve yoğunluğunu gösteren vektör."]],
      sources: [commonSources.physics2],
    },

    "entropi-ve-istatistiksel-fizik": {
      mark: "S",
      field: "İleri fizik · Durak 02",
      title: "Entropi ve istatistiksel fizik",
      description: "Mikroskobik olasılıkların makroskobik sıcaklık, basınç ve zaman oku hâline nasıl geldiğini parçacık laboratuvarıyla keşfet.",
      question: "Moleküler yasalar zaman yönünü ayırt etmiyorsa kırılan bir bardağın kendiliğinden birleşmesini neden görmeyiz?",
      questionDetail: "İkinci yasa mikroskobik hareketi yasaklayan yeni bir kuvvet değildir. Çok sayıda parçacığın ezici çoğunlukla daha fazla mikroduruma karşılık gelen makrodurumlara evrilmesinin istatistiksel ifadesidir.",
      level: "Lise ileri–Lisans",
      duration: "70 dakika",
      labLabel: "Mikrodurum sayacı",
      prerequisites: [{ href: "termodinamik.html", label: "Termodinamik" }, { href: "pascal-ucgeni.html", label: "Kombinatorik" }, { href: "normal-dagilim.html", label: "Olasılık dağılımları" }],
      goals: [["Ölçekleri ayır", "Makrodurumla onu gerçekleştiren mikrodurumları ayır."], ["Entropiyi say", "S=kᴮ lnΩ bağıntısını erişilebilir mikrodurum sayısıyla ilişkilendir."], ["İkinci yasayı yorumla", "Entropi artışını kesin tek-yörünge yasağı değil, çok güçlü olasılık eğilimi olarak açıkla."], ["Enerji ile bağla", "Sıcaklığı enerji paylaşımına ilişkin türevsel bir nicelik olarak yorumla."]],
      sections: [
        { kicker: "1 · İki betimleme düzeyi", title: "Makrodurumun altında kaç dünya var?", paragraphs: ["Bir gazın basıncı, hacmi ve sıcaklığı makroskobik birkaç sayıdır. Oysa mikrodurum, her parçacığın konum ve momentumunu belirtir. Aynı makrodurumu gerçekleştiren astronomik sayıda farklı mikrodurum olabilir.", "Bir kutuyu iki yarıya ayırıp N ayırt edilebilir parçacığın yalnız hangi tarafta olduğunu kaydedelim. Solda n parçacık bulunan makrodurumun çokluğu Ω=C(N,n)'dir. N/2–N/2 gibi dengeli dağılımların çokluğu, bütün parçacıkların tek tarafta olmasından çok daha büyüktür."], equation: "Ω(N,n)=N!/[n!(N−n)!]", equationNote: "Bu oyuncak model konum ve momentum ayrıntılarını yok sayar; yalnız kombinatorik fikri görünür kılar." },
        { kicker: "2 · Entropi", title: "Çarpımları toplama dönüştüren ölçü", paragraphs: ["Boltzmann bağıntısı S=kᴮ lnΩ, bir makroduruma karşılık gelen erişilebilir mikrodurumların sayısını entropiye bağlar. Logaritma önemlidir: bağımsız A ve B sistemlerinde çokluklar ΩᴬΩᴮ ile çarpılırken entropiler toplanır.", "Entropiyi yalnız ‘düzensizlik’ diye çevirmek çoğu durumda yanıltıcıdır. Daha güvenli ifade, verilen makroskobik kısıtlarla uyumlu mikrodurum çokluğunun ölçüsüdür. Düzen sezgisi bazı örneklerde işe yarasa da karışım, faz geçişi veya bilgi problemlerinde belirsizleşir."], equation: "S=kᴮ lnΩ", equationNote: "kᴮ birim dönüşümünü sağlar. Kuantum ve sürekli klasik durumlarda Ω'nın tanımı uygun durum sayımı/ölçüsüyle yapılır." },
        { kicker: "3 · İkinci yasa", title: "Kesinlik değil, ezici çoğunluk", paragraphs: ["Yalıtılmış makroskobik bir sistem düşük çokluklu bir durumdan başladığında, erişebileceği mikrodurumların ezici çoğunluğu daha büyük çokluklu makrodurumlara aittir. Bu nedenle dengeye doğru hareket gözlenir ve toplam entropinin azalmaması beklenir.", "Küçük sistemlerde kısa süreli entropi dalgalanmaları mümkündür. İkinci yasa ‘hiçbir parçacık geri dönemez’ demez. 10²³ mertebesinde parçacık için büyük bir ters dalgalanmanın olasılığı pratikte ölçülemeyecek kadar küçüktür. Zaman oku bu olasılık asimetrisinde belirginleşir."], equation: "ΔSₜₒₚₗₐₘ ≥ 0 &nbsp; (yalıtılmış makroskobik sistem)", equationNote: "Eşitlik tersinir ideal sınırda, büyüme ise gerçek tersinmez süreçlerde kullanılır." },
        { kicker: "4 · Sıcaklık ve enerji paylaşımı", title: "Denge, en olası enerji bölüşümüdür", paragraphs: ["Enerji alışverişi yapabilen iki sistemin toplam enerjisi sabitse, denge toplam mikrodurum sayısını en büyük yapan paylaşımda oluşur. Bu maksimum koşulundan iki sistem için ∂S/∂U değerlerinin eşitliği çıkar.", "Termodinamik sıcaklık 1/T=(∂S/∂U)ᴠ,ᴺ ile tanımlanır. Enerji, 1/T'si küçük olan sistemden büyük olana değil; sıcak olandan soğuk olana akar ve toplam entropiyi artırır. Negatif mutlak sıcaklık yalnız üstten sınırlı enerji düzeylerine sahip özel sistemlerde tanımlanabilir ve ‘sıfırdan daha soğuk’ değildir."], equation: "1/T = (∂S/∂U)ᵥ,ₙ", equationNote: "Türevin pozitif olduğu sıradan sistemlerde enerji arttıkça entropi artar; tanım denge termodinamiğine aittir." },
      ],
      worked: { title: "Çözülmüş örnek · Dört parçacığın iki bölmesi", intro: "Dört ayırt edilebilir parçacığın sol/sağ konumlarını sayalım.", steps: ["Toplam 2⁴=16 mikrodurum vardır.", "4–0 dağılımının Ω=C(4,4)=1; 3–1 dağılımının Ω=C(4,3)=4 mikrodurumu vardır.", "2–2 dağılımı Ω=C(4,2)=6 ile en olası tek makrodurumdur.", "N büyüdükçe göreli dağılım n/N, 1/2 çevresinde çok daha keskin yoğunlaşır; makroskobik denge güvenilir görünür."] },
      misconceptions: [["Entropi her zaman gözle görülen dağınıklıktır.", "Entropi, belirli kısıtlar altındaki mikrodurum çokluğu ve enerji dağılımıyla tanımlanır; görsel dağınıklık evrensel ölçüt değildir."], ["İkinci yasa küçük sistemde hiçbir ters dalgalanmaya izin vermez.", "Yasa istatistikseldir; küçük ölçeklerde dalgalanmalar ölçülebilir, büyük ölçeklerde göreli etkileri kaybolur."]],
      limits: [["Oyuncak model", "Laboratuvar parçacıkların yalnız sol/sağ bilgisini sayar; gerçek gazın sürekli konum ve momentum durumları vardır."], ["Denge varsayımı", "Hızla sürülen, canlı veya aktif maddeler gibi dengeden uzak sistemler ek değişkenler ve üretim terimleri gerektirir."]],
      lab: { type: "entropy", title: "Olasılık zaman okunu nasıl kurar?", intro: "Parçacık sayısını ve sol bölmedeki sayıyı değiştir. Makrodurum çokluğunu ve toplam olasılık içindeki payını karşılaştır." },
      connections: [["termodinamik.html", "Termodinamik", "Isı, iş ve durum fonksiyonlarını makro dille incele."], ["kimyasal-denge-ve-gibbs-enerjisi.html", "Kimyasal denge", "Entropi ile enerjinin tepkime yönünü birlikte nasıl seçtiğini gör."], ["rastgele-yuruyus.html", "Rastgele yürüyüş", "Çok sayıda rastgele adımın düzenli istatistik üretmesini izle."]],
      quiz: [["S=kᴮlnΩ bağıntısında Ω neyi sayar?", ["Yalnız parçacık sayısını", "Makrodurumla uyumlu erişilebilir mikrodurumları", "Sistemin hacmini"], 1, "Ω aynı makroskobik bilgilerle uyumlu mikroskobik düzenlemelerin çokluğudur."], ["Dengeli bölüşüm neden büyük N'de baskındır?", ["Daha çok mikrodurumla gerçekleşir", "Parçacıklar saymayı bilir", "Enerji korunmaz"], 0, "Kombinatorik olarak orta bölüşümlere karşılık gelen düzenleme sayısı çok büyüktür."], ["İkinci yasa en doğru nasıl okunur?", ["Her molekül hep daha düzensiz hareket eder", "Yalıtılmış makroskobik sistem büyük olasılıkla yüksek çokluklu durumlara gider", "Enerji zamanla yok olur"], 1, "Mikroskobik enerji korunurken makrodurumların olasılık ağırlıkları zaman okunu üretir."]],
      glossary: [["Mikrodurum", "Sistemin mikroskobik serbestliklerinin ayrıntılı düzeni."], ["Makrodurum", "Basınç, sıcaklık gibi az sayıda toplu nicelikle tanımlanan durum."], ["Çokluk", "Bir makrodurumu gerçekleştiren mikrodurum sayısı."], ["Entropi", "Erişilebilir durum çokluğunun logaritmik termodinamik ölçüsü."]],
      sources: [commonSources.physics1],
    },

    "kimyasal-denge-ve-gibbs-enerjisi": {
      mark: "G",
      field: "Fiziksel kimya · Durak 01",
      title: "Kimyasal denge ve Gibbs enerjisi",
      description: "Denge sabitini tepkimenin durduğu bir nokta değil, ileri ve geri süreçlerin dinamik dengesi olarak gör; Q, K ve ΔG ilişkisini keşfet.",
      question: "Bir tepkimenin hangi yöne ilerleyeceğini yalnız başlangıç derişimlerine ve sıcaklığa bakarak nasıl öngörebiliriz?",
      questionDetail: "Tepkime bölümü Q, o andaki bileşimi; denge sabiti K ise verilen sıcaklıktaki denge bileşimi ölçütünü taşır. Gibbs enerjisi bu iki bilgiyi tek bir yön göstergesinde birleştirir.",
      level: "Lise ileri–Lisans",
      duration: "65 dakika",
      labLabel: "Q–K yön bulucu",
      prerequisites: [{ href: "kimyasal-kinetik.html", label: "Kimyasal kinetik" }, { href: "termodinamik.html", label: "Termodinamik" }, { href: "ideal-gaz.html", label: "İdeal gaz" }],
      goals: [["Dinamik dengeyi açıkla", "Dengede ileri ve geri hızların eşit, derişimlerin ise zorunlu olarak eşit olmadığını söyle."], ["Q ile K'yı karşılaştır", "Anlık bileşimden tepkimenin net yönünü belirle."], ["Enerji bağını kur", "ΔG=ΔG°+RTlnQ ve ΔG°=−RTlnK ilişkilerini yorumla."], ["Bozucu etkiyi izle", "Sıcaklık, basınç ve bileşim değişiminin dengeye etkisini doğru koşullarla açıkla."]],
      sections: [
        { kicker: "1 · Denge hareketlidir", title: "İki yön, eşit hız", paragraphs: ["Kapalı bir sistemde tersinir tepkime ilerledikçe girenler azalır, ürünler artar. İleri hız genellikle düşerken geri hız yükselir. Denge anında bu iki hız eşittir; moleküler dönüşümler sürer ama makroskobik derişimler zamanla sabit kalır.", "Dengede giren ve ürün derişimlerinin eşit olması gerekmez. Hangi tarafın baskın olduğu denge sabitine ve stokiyometriye bağlıdır. K çok büyükse ürünler, çok küçükse girenler baskındır; yine de çoğu durumda her iki tarafın da sıfırdan farklı miktarı bulunur."], equation: "aA+bB ⇌ cC+dD", equationNote: "Denge dinamiktir: vᵢleri=vgeri, fakat tek tek moleküller dönüşmeye devam eder." },
        { kicker: "2 · Tepkime bölümü", title: "Q, sistemin şu an nerede olduğunu söyler", paragraphs: ["İdeal seyreltik çözelti yaklaşımında Q, ürün etkinliklerinin stokiyometrik kuvvetlerinin çarpımının girenlerinkine oranıdır. Saf katı ve saf sıvıların etkinliği standart durumda yaklaşık 1 kabul edildiği için denge ifadesinde görünmezler.", "Q<K ise tepkime bölümü denge değerine ulaşmak için net olarak ürünlere; Q>K ise girenlere yönelir. Q=K olduğunda ΔG=0 ve sistem dengededir. Bu karşılaştırma ‘Le Châtelier ezberi’nden daha genel ve nicel bir yön testidir."], equation: "Q=(aᶜ_C aᵈ_D)/(aᵃ_A aᵇ_B); &nbsp; dengede Q=K", equationNote: "Derişimleri doğrudan kullanmak bir ideal yaklaşım olabilir; hassas hesaplarda boyutsuz etkinlikler kullanılır." },
        { kicker: "3 · Gibbs enerjisi", title: "Enerji ve entropi aynı ölçütte", paragraphs: ["Sabit sıcaklık ve basınçta bir sürecin kendiliğinden ilerleme yönünü Gibbs enerji değişimi belirler. ΔG<0 ileri yön, ΔG>0 geri yön için termodinamik eğilim; ΔG=0 denge demektir. Bu, tepkimenin hızlı olacağını söylemez: kinetik bariyer ayrı sorudur.", "Standart Gibbs değişimi ΔG°, tüm bileşenlerin standart durumda olduğu referans farkıdır. Gerçek karışımın bileşimi RTlnQ terimiyle eklenir. Dengede ΔG=0 ve Q=K yazılırsa ΔG°=−RTlnK çıkar. Büyük K, standart koşullarda daha negatif ΔG° ile ilişkilidir."], equation: "ΔG=ΔG°+RT lnQ; &nbsp; ΔG°=−RT lnK", equationNote: "K yalnız sıcaklığa bağlıdır; Q bileşim değiştikçe değişir. Logaritmanın argümanı boyutsuz etkinlik oranıdır." },
        { kicker: "4 · Sistemi değiştirmek", title: "Bileşim, basınç ve sıcaklık aynı şey değildir", paragraphs: ["Bir madde eklemek Q'yu anında değiştirir; sistem daha sonra yeniden Q=K olana kadar tepki verir. Gaz tepkimelerinde hacmi azaltmak tüm kısmi basınçları etkiler; net gaz molü daha az olan taraf genellikle desteklenir. İnert gaz eklemenin etkisi sabit hacim ve sabit basınç koşullarında farklıdır.", "Sıcaklık değişimi yalnız Q'yu değil <strong>K'yı da</strong> değiştirir. Endotermik ileri tepkimede sıcaklık artışı çoğunlukla K'yı artırır; ekzotermikte azaltır. Katalizör ileri ve geri yolların aktivasyon enerjisini düşürerek dengeye erişimi hızlandırır, fakat K'yı veya denge bileşimini değiştirmez."], note: "Kritik ayrım: Termodinamik ‘hangi yön elverişli?’, kinetik ‘hangi hızla?’ sorusunu yanıtlar." },
      ],
      worked: { title: "Çözülmüş örnek · Tepkime hangi yöne gider?", intro: "A(g) ⇌ B(g) için 298 K'de K=4,0; o anda pᴬ/p°=0,50 ve pᴮ/p°=1,00 olsun.", steps: ["Q=(pᴮ/p°)/(pᴬ/p°)=1,00/0,50=2,0.", "Q<K olduğundan net değişim ürün B yönündedir.", "ΔG=RTln(Q/K)=RTln(0,5)<0; aynı yön kararını enerji diliyle verir.", "Dengeye ulaşıldığında ileri ve geri hızlar eşitlenir, Q 4,0 olur; basınçların eşit olması gerekmez."] },
      misconceptions: [["Dengede tepkime durur.", "İleri ve geri moleküler süreçler sürer; yalnız net makroskobik değişim sıfırdır."], ["Katalizör dengeyi ürünlere kaydırır.", "Katalizör iki yönü de hızlandırır; aynı sıcaklıkta K ve denge bileşimi değişmez."]],
      limits: [["İdeal davranış", "Derişim/basınçla yazılan basit ifadeler ideal yaklaşımı kullanır; yoğun çözeltilerde etkinlik katsayıları gerekir."], ["Termodinamik–kinetik ayrımı", "Negatif ΔG hızlı tepkime garantisi değildir; elmasın grafite dönüşümü termodinamikçe elverişli olup kinetikçe çok yavaş olabilir."]],
      lab: { type: "equilibrium", title: "Tepkimenin pusulası: ΔG", intro: "Standart Gibbs enerjisini, sıcaklığı ve Q'yu değiştir. Laboratuvar K'yı hesaplar ve sistemin net hangi yöne eğilimli olduğunu gösterir." },
      connections: [["entropi-ve-istatistiksel-fizik.html", "Entropi", "Dengenin neden en olası enerji ve madde paylaşımı olduğunu derinleştir."], ["kimyasal-kinetik.html", "Kimyasal kinetik", "Elverişli bir tepkimenin neden yine de yavaş olabileceğini gör."], ["asit-baz-titrasyonu.html", "Asit–baz dengesi", "Denge sabitini pH ve tampon sistemlerinde uygula."]],
      quiz: [["Q<K ise net termodinamik eğilim hangi yöndedir?", ["Ürünler", "Girenler", "Hiçbir yön"], 0, "Q'nun K'ya yükselmesi için ürün/giren etkinlik oranı artmalıdır."], ["Dengede hangisi doğrudur?", ["İleri ve geri hızlar eşittir", "Bütün derişimler eşittir", "Moleküler hareket durur"], 0, "Dinamik dengede zıt yönlü hızlar eşittir; derişimler sabit ama zorunlu olarak eşit değildir."], ["Katalizör neyi değiştirir?", ["K'yı", "ΔG°'yi", "Dengeye ulaşma süresini"], 2, "Katalizör kinetik yolu değiştirir; aynı sıcaklıkta termodinamik dengeyi değiştirmez."]],
      glossary: [["Etkinlik", "Bir bileşenin kimyasal potansiyelini belirleyen boyutsuz etkin derişim."], ["Tepkime bölümü", "Anlık bileşimden hesaplanan ürün/giren etkinlik oranı."], ["Denge sabiti", "Belirli sıcaklıkta Q'nun denge değeri."], ["Gibbs enerjisi", "Sabit T ve p koşullarında kendiliğinden yönü ve erişilebilir işi belirleyen durum fonksiyonu."]],
      sources: [commonSources.chemistry],
    },

    "gen-ifadesi-ve-molekuler-biyoloji": {
      mark: "RNA",
      field: "Moleküler biyoloji · Durak 01",
      title: "Gen ifadesi ve moleküler bilgi akışı",
      description: "DNA'daki dizinin ne zaman RNA'ya, RNA'nın ne zaman proteine dönüştürüldüğünü; düzenleme, geri besleme ve rastlantısallıkla birlikte öğren.",
      question: "Aynı DNA'yı taşıyan bir sinir hücresiyle kas hücresi nasıl bu kadar farklı davranabilir?",
      questionDetail: "Hücre kimliği yalnız hangi genlerin bulunduğuyla değil, hangi genlerin ne zaman, nerede ve ne miktarda ifade edildiğiyle belirlenir. Gen düzenleme; sinyalleri DNA erişilebilirliğine, RNA üretimine ve protein miktarına çeviren çok katmanlı bir sistemdir.",
      level: "Lise ileri–Lisans",
      duration: "70 dakika",
      labLabel: "mRNA–protein dinamiği",
      prerequisites: [{ href: "dna-replikasyon.html", label: "DNA eşlenmesi" }, { href: "enzim-kinetigi.html", label: "Enzimler" }],
      goals: [["Süreçleri ayır", "Eşlenme, transkripsiyon ve translasyonun girdilerini, ürünlerini ve amaçlarını karşılaştır."], ["Düzenleme katmanlarını gör", "Kromatin erişiminden protein yıkımına kadar ifadenin kontrol noktalarını sırala."], ["Kodun sınırını açıkla", "Bir genin tek ve değişmez bir protein demek olmadığını alternatif işlenme ve düzenleme üzerinden göster."], ["Dinamiği yorumla", "Üretim ve yıkım hızlarının mRNA/protein düzeyini nasıl belirlediğini modelle."]],
      sections: [
        { kicker: "1 · Bilgi akışı", title: "DNA saklar, RNA taşır ve işler, protein iş görür", paragraphs: ["DNA eşlenmesi genomu yeni hücrelere aktarır; transkripsiyon belirli DNA bölgesinden RNA üretir; translasyon mRNA kodon dizisini amino asit dizisine çevirir. Bu üç süreç aynı şey değildir ve farklı enzim makineleri kullanır.", "‘Merkezî dogma’ dizisel bilginin genel akışını DNA→RNA→protein olarak özetler; bütün biyolojiyi tek okla açıklamaz. Ters transkriptaz RNA'dan DNA üretebilir. Proteinler ve kodlamayan RNA'lar hangi genlerin ifade edileceğini düzenler. Çevresel bilgi, diziyi hedefli biçimde proteinden DNA'ya geri yazmak zorunda olmadan gen ifadesini değiştirebilir."], equation: "DNA —transkripsiyon→ RNA —translasyon→ protein", equationNote: "Oklar madde dönüşümünü değil, dizisel bilginin kalıp aracılığıyla aktarım yönünü gösterir." },
        { kicker: "2 · Bir gen ne zaman açılır?", title: "Promotör, düzenleyici diziler ve kromatin", paragraphs: ["RNA polimeraz transkripsiyona promotör yakınında başlar. Transkripsiyon faktörleri belirli DNA dizilerine bağlanarak makinenin toplanmasını kolaylaştırabilir veya engelleyebilir. Ökaryotlarda uzaktaki artırıcılar DNA'nın üç boyutlu katlanmasıyla promotörlere yaklaşabilir.", "DNA'nın histonlarla paketlenmesi erişilebilirliği etkiler. Histon değişimleri ve DNA metilasyonu düzenleyici durumla ilişkilidir; fakat tek bir ‘etiket=gen kapalı’ kuralı her bağlamda geçerli değildir. Epigenetik, DNA dizisi değişmeden sürdürülebilen düzenleme durumlarını inceler; bütün çevresel etkilerin kalıtsal olması demek değildir."], note: "Bağlam önemlidir: Aynı transkripsiyon faktörü, ortakları ve bağlandığı düzenleyici mimariye göre farklı sonuçlar doğurabilir." },
        { kicker: "3 · RNA tek bir ara basamak değildir", title: "İşlenme, çeşitlilik ve kalite kontrol", paragraphs: ["Ökaryotik öncül mRNA'ya 5′ başlık ve poli(A) kuyruğu eklenir; intronlar çıkarılıp ekzonlar birleştirilir. Alternatif kesip birleştirme, aynı genden farklı RNA ve protein izoformları üretebilir. Bu nedenle ‘bir gen = bir protein’ öğretici bir başlangıç olsa da genel olarak doğru değildir.", "mRNA'nın hücredeki konumu ve yarı ömrü, ne kadar protein üretileceğini etkiler. MikroRNA'lar ve RNA bağlayıcı proteinler translasyonu veya yıkımı düzenleyebilir. Hatalı RNA ve proteinler kalite kontrol yollarıyla tanınır; bu sistemlerin aksaması hastalıkla ilişkilendirilebilir."], equation: "dm/dt=α−δₘm; &nbsp; dp/dt=βm−δₚp", equationNote: "Basit modelde α transkripsiyon, β translasyon; δₘ ve δₚ yıkım sabitleridir. Gerçek düzenleme çoğunlukla doğrusal değildir." },
        { kicker: "4 · Ağlar ve gürültü", title: "Genler tek başına değil, devreler içinde davranır", paragraphs: ["Bir protein kendi geninin ifadesini bastırırsa negatif geri besleme oluşur; bu, yanıtı hızlandırabilir ve dalgalanmayı azaltabilir. Pozitif geri besleme iki kararlı durum ve hücresel hafıza üretebilir. Gecikmeli negatif geri besleme salınım yaratabilir; sirkadiyen saat ağları buna örnektir.", "Molekül sayıları az olduğunda transkripsiyon ve translasyon olayları rastlantısaldır. Aynı koşuldaki genetik olarak özdeş hücreler farklı protein düzeylerine sahip olabilir. Bu ‘gürültü’ yalnız ölçüm hatası değildir; hücresel kararları etkileyen biyolojik bir özellik olabilir."], equation: "Durağan basit model: m*=α/δₘ, &nbsp; p*=βα/(δₘδₚ)", equationNote: "Bu sonuç sabit hızlar, iyi karışmış hücre ve geri beslemesiz deterministik model varsayar." },
      ],
      worked: { title: "Çözülmüş örnek · Bir proteinin yeni denge düzeyi", intro: "Transkripsiyon hızı iki katına çıkıyor; diğer bütün hız sabitleri değişmiyor.", steps: ["Başlangıç durağan mRNA düzeyi m*=α/δₘ'dir.", "α iki katına çıkınca yeni mRNA dengesi 2m* olur.", "Protein dengesi p*=βm*/δₚ olduğundan yeni protein düzeyi de ideal modelde iki katına çıkar.", "Geçiş anlık değildir: mRNA ve protein kendi yarı ömürleriyle yeni düzeye yaklaşır. Doygunluk veya geri besleme varsa iki kat yanıt beklenmeyebilir."] },
      misconceptions: [["Her gen yalnız bir protein üretir.", "Alternatif RNA işlenmesi, farklı başlangıç/bitişler ve protein değişimleri bir genden birden fazla ürün oluşturabilir."], ["Bir hücrenin bütün genleri sürekli okunur.", "Gen ifadesi hücre tipine, gelişim evresine, sinyallere ve kromatin durumuna göre seçici biçimde düzenlenir."]],
      limits: [["Ortalama alan modeli", "Laboratuvar hücreyi iyi karışmış kabul eder ve ortalama molekül düzeylerini gösterir; tek hücre gürültüsünü doğrudan simüle etmez."], ["Dizi kader değildir", "DNA dizisi önemlidir; ancak fenotip düzenleyici ağ, hücresel ortam, gelişim ve çevre etkileşiminin sonucudur."]],
      lab: { type: "gene", title: "Üretim ve yıkım arasında ifade", intro: "Transkripsiyon, translasyon ve protein yıkım hızlarını değiştir. mRNA'nın önce, proteinin gecikerek yeni dengeye nasıl yaklaştığını izle." },
      connections: [["dna-replikasyon.html", "DNA eşlenmesi", "Genomun kopyalanmasıyla ifade edilmesi arasındaki farkı pekiştir."], ["enzim-kinetigi.html", "Enzim kinetiği", "Protein miktarı ile tepkime akısı arasındaki bağı incele."], ["dogal-secilim.html", "Evrim", "Düzenleyici dizilerdeki değişimin fenotipi nasıl etkileyebileceğini düşün."]],
      quiz: [["Aynı genin farklı protein izoformları üretmesinin bir yolu nedir?", ["Alternatif kesip birleştirme", "DNA'nın her seferinde yok olması", "Bütün kodonların aynı amino asidi vermesi"], 0, "Farklı ekzon birleşimleri farklı olgun mRNA ve protein ürünleri oluşturabilir."], ["Basit dm/dt=α−δm modelinde durağan mRNA düzeyi nedir?", ["αδ", "α/δ", "δ/α"], 1, "Durağan durumda üretim ve yıkım eşittir: α=δm."], ["Negatif geri besleme ne yapabilir?", ["Her zaman sınırsız büyüme", "Yanıtı hızlandırıp dalgalanmayı azaltma", "DNA dizisini zorunlu olarak değiştirme"], 1, "Ürün kendi üretimini bastırdığında sapmalar dengelenebilir ve yanıt süresi kısalabilir."]],
      glossary: [["Promotör", "Transkripsiyon makinesinin kurulmasını yönlendiren DNA bölgesi."], ["Transkripsiyon faktörü", "Belirli DNA bölgelerine bağlanıp gen ifadesini etkileyen protein."], ["Alternatif kesip birleştirme", "Aynı öncül RNA'dan farklı ekzon bileşimleri üretme süreci."], ["Gen düzenleyici ağ", "Genlerin ve ürünlerinin birbirinin ifadesini etkilediği etkileşim sistemi."]],
      sources: [commonSources.biology],
    },

    "algoritma-karmasikligi": {
      mark: "O",
      field: "Bilgisayar bilimi · Durak 01",
      title: "Algoritma karmaşıklığı ve ölçeklenme",
      description: "Bir programın yalnız çalışıp çalışmadığını değil, girdi büyüdükçe zaman ve bellek gereksiniminin nasıl büyüdüğünü deneysel grafiklerle incele.",
      question: "Aynı doğru cevabı veren iki algoritmadan hangisinin milyon kat büyük veride hâlâ kullanılabilir kalacağını nasıl anlarsın?",
      questionDetail: "Karmaşıklık analizi belirli bir bilgisayardaki saniyeyi değil, kaynak kullanımının girdi boyutuyla büyüme biçimini inceler. Sabit katsayılar küçük girdide önemli olabilir; büyüme sınıfı ise ölçek değiştiğinde belirleyici olur.",
      level: "Lise ileri–Lisans",
      duration: "60 dakika",
      labLabel: "Büyüme sınıfları karşılaştırıcısı",
      prerequisites: [{ href: "algoritmalar.html", label: "Algoritmalar" }, { href: "fonksiyon-grafigi.html", label: "Fonksiyonlar" }, { href: "veri-yapilari.html", label: "Veri yapıları" }],
      goals: [["Boyut seç", "Bir problem için anlamlı girdi boyutu n'nin ne olduğunu açıkça tanımla."], ["Büyüme sınıfını oku", "O, Ω ve Θ gösterimlerinin üst, alt ve sıkı asimptotik sınır rollerini ayır."], ["Durumları karşılaştır", "En kötü, ortalama ve amorti edilmiş analizlerin farklı sorular yanıtladığını açıkla."], ["Deneyle doğrula", "Çalışma süresi ölçümünü ısınma, gürültü ve veri dağılımı gibi etkenlerle birlikte yorumla."]],
      sections: [
        { kicker: "1 · Kaynak büyümesi", title: "Saniye değil, ölçek sorusu", paragraphs: ["Bir algoritmanın çalışma süresini T(n) ile gösterelim. n liste uzunluğu, düğüm sayısı, bit sayısı veya matris boyutu olabilir; doğru tanım probleme bağlıdır. Asimptotik analiz n büyürken baskın terime odaklanır. 3n²+20n+500, Θ(n²)'dir.", "Bu yaklaşım sabit katsayıları önemsiz ilan etmez. Küçük n'de iyi uygulanmış n² algoritması kötü uygulanmış n log n algoritmasını geçebilir. Donanım, önbellek ve paralellik gerçek zamanı etkiler. Fakat n on kat büyüdüğünde n² maliyet yüz kat, n log n maliyet yaklaşık on birkaç kat büyür."], equation: "T(n)=3n²+20n+500 ∈ Θ(n²)", equationNote: "Θ sıkı büyüme sınıfıdır: yeterince büyük n için T(n), n²'nin pozitif sabit katları arasında kalır." },
        { kicker: "2 · Üç asimptotik dil", title: "O, Ω ve Θ aynı şey değildir", paragraphs: ["T(n)∈O(g(n)), yeterince büyük n için T'nin g'nin sabit katından hızlı büyümediğini söyler: asimptotik üst sınırdır. Ω alt sınır, Θ ise hem üst hem alt sınırın birlikte sağlandığı sıkı sınıftır.", "Big-O günlük kullanımda çoğu kez ‘yaklaşık çalışma sınıfı’ anlamında söylenir, fakat matematiksel olarak sıkı olmak zorunda değildir. n log n aynı zamanda O(n²)'dir; daha bilgilendirici ifade Θ(n log n) olabilir. Logaritmanın tabanı asimptotik sınıfı değiştirmez, çünkü taban değişimi sabit katsayıdır."], equation: "c₁g(n) ≤ T(n) ≤ c₂g(n) &nbsp; (n≥n₀) ⇒ T(n)∈Θ(g(n))", equationNote: "Sabitler c₁,c₂>0 ve eşik n₀ seçilebilir olmalıdır." },
        { kicker: "3 · Hangi durum?", title: "En kötü, ortalama ve amorti edilmiş analiz", paragraphs: ["Doğrusal arama, aranan eleman ilk sıradaysa Θ(1), son sıradaysa Θ(n) sürer. En kötü durum garanti verir; ortalama durum için girdilerin olasılık dağılımını belirtmek gerekir. ‘Ortalama O(n)’ ifadesi, ortalamanın neye göre alındığı söylenmezse eksiktir.", "Amorti edilmiş analiz, tek bir işlemin olasılıksal ortalaması değildir. Dinamik dizide kapasite dolunca yeniden ayırma pahalıdır, fakat birçok ekleme boyunca nadir gerçekleşir; n eklemenin toplamı Θ(n), işlem başına amorti edilmiş maliyet Θ(1)'dir. Tek bir ekleme yine Θ(n) olabilir."], note: "Bir karmaşıklık iddiasının yanında problem modeli, girdi boyutu, maliyet modeli ve incelenen durum yazılmalıdır." },
        { kicker: "4 · Zaman–bellek ve çözülemez ölçek", title: "Hız kazanırken ne harcıyoruz?", paragraphs: ["Önceden hesaplanmış tablo veya karma tablosu daha fazla bellek kullanarak sorguyu hızlandırabilir. Dinamik programlama yinelenen alt problemleri saklar. Algoritma seçimi yalnız zaman karmaşıklığı değil; bellek, doğruluk, enerji, gecikme ve uygulama karmaşıklığı arasında bir dengedir.", "2ⁿ veya n! büyümesi, orta boyutta bile fiziksel sınırları aşar. Bu durumda daha hızlı donanım çoğu kez yetmez; problem yapısından yararlanan algoritma, yaklaşım, rastgeleleştirme veya parametreli yöntem gerekir. Karmaşıklık kuramı ayrıca bazı problemlerin bilinen bütün kesin algoritmalarının neden pahalı göründüğünü sınıflar."], equation: "n=60 için 2ⁿ ≈ 1,15×10¹⁸ olasılık", equationNote: "Saniyede bir milyar durum denetlense bile kaba tarama yaklaşık 36 yıl sürer; dağıtım sabit çarpanı iyileştirir, üstel sınıfı değiştirmez." },
      ],
      worked: { title: "Çözülmüş örnek · İki sıralama yaklaşımı", intro: "n=1.000 öğe için A algoritması yaklaşık n², B algoritması 30n log₂n işlem yapsın.", steps: ["A≈1.000.000 işlem.", "B≈30×1.000×9,97≈299.100 işlem; bu ölçekte B yaklaşık 3,3 kat daha azdır.", "n=1.000.000 olursa A≈10¹², B≈30×10⁶×19,93≈5,98×10⁸; fark yaklaşık 1.670 kata çıkar.", "B'nin sabit katsayısı 30 olmasına rağmen daha yavaş büyüyen sınıf büyük ölçekte baskın olur. Gerçek seçim için bellek ve veri özellikleri de ölçülmelidir."] },
      misconceptions: [["O(n²), algoritmanın tam n² adım sürdüğü anlamına gelir.", "Big-O sabitleri ve düşük mertebeli terimleri gizleyen asimptotik üst sınırdır; tam işlem sayısı değildir."], ["En kötü durum analizi algoritmanın her zaman o kadar yavaş olduğunu söyler.", "En kötü durum, seçilen n için garanti edilen üst davranıştır; tipik girdiler farklı olabilir."]],
      limits: [["Maliyet modeli", "Laboratuvar soyut işlem sayılarını karşılaştırır; önbellek, ağ, disk, derleyici ve paralellik gerçek süreyi değiştirebilir."], ["Asimptotik eşik", "Büyüme sınıfı yeterince büyük n içindir. Pratik girdi aralığında sabitler ve veri yapısı ayrıntıları belirleyici kalabilir."]],
      lab: { type: "complexity", title: "Girdi büyüdükçe yarış nasıl değişir?", intro: "n değerini artır; log n, n, n log n, n² ve 2ⁿ sınıflarının göreli maliyetini logaritmik ölçekte karşılaştır." },
      connections: [["veri-yapilari.html", "Veri yapıları", "Aynı işlemin farklı örgütlenmelerdeki maliyetini karşılaştır."], ["cizge-teorisi.html", "Çizge algoritmaları", "Düğüm ve kenar sayısıyla ölçeklenen arama problemlerini incele."], ["makine-ogrenmesi-derin-ogrenme-llm.html", "Makine öğrenmesi", "Eğitim ve çıkarım maliyetini veri, parametre ve hesap ölçeğiyle düşün."]],
      quiz: [["3n²+20n+500 için en bilgilendirici sıkı sınıf hangisidir?", ["Θ(n)", "Θ(n²)", "Θ(2ⁿ)"], 1, "Büyük n'de n² terimi baskındır; pozitif sabit katsayı sınıfı değiştirmez."], ["Amorti edilmiş Θ(1) ekleme neyi garanti etmez?", ["Uzun işlem dizisinin toplamda doğrusal olmasını", "Her tek eklemenin Θ(1) olmasını", "Nadir pahalı yeniden ayırmaların dengelenmesini"], 1, "Tek bir yeniden ayırma Θ(n) olabilir; sabit maliyet birçok işlem üzerine dağıtılır."], ["n log n algoritması neden aynı zamanda O(n²)'dir?", ["n log n yeterince büyük n'de n² ile üstten sınırlanır", "Logaritma her zaman sıfırdır", "İki sınıf eşittir"], 0, "Big-O sıkı olmak zorunda değildir; n² geçerli ama daha gevşek bir üst sınırdır."]],
      glossary: [["Girdi boyutu", "Problemin ölçeğini temsil eden açıkça tanımlanmış n ölçüsü."], ["Asimptotik analiz", "n büyürken kaynak kullanımının baskın büyüme davranışını inceleme."], ["Amorti edilmiş maliyet", "Bir işlem dizisinin toplam maliyetini işlemlere dağıtan en kötü-dizi analizi."], ["Uzay karmaşıklığı", "Algoritmanın girdi boyutuna bağlı ek bellek gereksinimi."]],
      sources: [commonSources.algorithms],
    },
  };
})();
